web/web/Models/fn_get_att_Result.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    
    public partial class fn_get_att_Result
    {
        public int sub_id { get; set; }
        public int stu_id { get; set; }
        public int tea_id { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string att_type { get; set; }
        public string att_description { get; set; }
    }
}

web/web/Controllers/StudentSubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Models;

namespace web.Controllers
{
    public class StudentSubjectController : Controller
    {
        // GET: StudentSubject
        public ActionResult Subject()
        {
           
            return View();
        }
    }
}

web/web/Views/StudentSubject/Subject.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Document</title>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Main","Main")">
            <img src="~/img/logo1.png" alt="" height="90px" width="190px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Subject","StudentSubject")">Subject <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Schedule","Schedule")">Schedule</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Assignment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Attendance</a>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Main","Main")'">Logout</button>
                </li>
            </ul>
        </div>
    </nav>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Menu","Menu")">Menu</a></li>
            <li class="breadcrumb-item active" aria-current="page">Subjects</li>
        </ol>
    </nav>
    <!--content-->
    <!-- <div class="container-fluid"> -->
    <!--row1-->
    <!-- <div class="row">
          <div class="col-sm-3 mt-3 ml-5 content">
              <div class="box">
                  <div class="float-left"><img class="card-img-top img-fluid" src="img/testsubject.jpeg"></div>
                  <div>
                      <h4 class="card-text">Object Oriented Analaysis and Design</h4>
                  </div>
              </div>
          </div>
          <div class="col-sm-3 mt-3 content">
              <div class="box">
                  <div class="float-left"><img class="card-img-top img-fluid" src="img/testsubject.jpeg"></div>
                  <div>
                      <h4 class="card-text">Web Application Development</h4>
                  </div>
              </div>
          </div>
          <div class="col-sm-3 mt-3 content">
              <div class="box">
                  <div class="float-left"><img class="card-img-top img-fluid" src="img/testsubject.jpeg"></div>
                  <div>
                      <h4 class="card-text">Software Engineering and IT Project management</h4>
                  </div>
              </div>
          </div>
        </div> -->
    <!--row2-->
    <!-- Vuthy Test -->
    <div class="container">
        <div class="containerMargin">
            <div class="row">
                <div class="col-md-4">
                    <a href="">
                    <div class="SubjectBackground">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="~/img/ooad.png" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <p class="text-white" style="padding: 13px;">Object Oriented Analysis and Design</p>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="">
                    <div class="SubjectBackground">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="~/img/web.png" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <p class="text-white" style="padding: 13px;">Web Application Development</p>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="">
                    <div class="SubjectBackground">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="~/img/SE.png" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <p class="text-white" style="padding: 9px;">Software Engineering and IT Project Management</p>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-4">
                    <a href="">
                    <div class="SubjectBackground">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="~/img/Linux.png" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <p class="text-white" style="padding: 13px;">Linux Sytem Administration</p>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="">
                    <div class="SubjectBackground">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="~/img/MIS.png" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <p class="text-white" style="padding: 13px;">Management Information System</p>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!--footer-->
    <footer class="page-footer font-small cyan darken-3 special-color-dark ">
        <center>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 py-5">
                        <div class="flex-center">
                            <a class="fb-ic">
                                <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                            </a>
                            <a class="tw-ic">
                                <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                            </a>
                            <a class="gplus-ic">
                                <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                            </a>
                            <a class="li-ic">
                                <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                            </a>
                            <a class="ins-ic">
                                <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                            </a>
                            <a class="pin-ic">
                                <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center py-3">
                <span>2018 © Royal University of Phnom Penh</span>
            </div>
        </center>
    </footer>

</body>

</html>